<body>
    <header class="navbar">
        <div class="nav-logo">
            <a href="index.php">
                <img src="./assets/images/BookVerse.svg" alt="Logo" class="logo-img">
                <span class="site-title">BookVerse</span>
            </a>
        </div>

        <nav aria-label="Main navigation">
            <ul class="nav-links">
                <li><a href="index.php"><img src="./assets/images/home.svg" class="nav-link-icon"
                            aria-hidden="true"></img>Home</a></li>
                <li><a href="books.php"><img src="./assets/images/browse.svg" class="nav-link-icon"
                            aria-hidden="true"></img>Browse Books</a></li>
                <li><a href="gallery.php"><img src="./assets/images/galleryIcon.svg" class="nav-link-icon"
                            aria-hidden="true"></img>Gallery</a></li>
                <li><a href="add.php"><img src="./assets/images/add.svg" class="nav-link-icon"
                            aria-hidden="true"></img>Add Book</a></li>
            </ul>
        </nav>
    </header>